#ifndef __EFSL_CONFIG_H__
#define __EFSL_CONFIG_H__
#define HW_ENDPOINT_LINUX
#define IOMAN_NUMBUFFER 98
#define CLUSTER_PREALLOC_FILE 62
#define CLUSTER_PREALLOC_DIRECTORY 62
#define IOMAN_NUMITERATIONS 3
#define IOMAN_DO_MEMALLOC
#define LITTLE_ENDIAN
#endif
